nindie/account/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^dashboard/$', views.index, name="index"),
    url(r'^settings/$', views.settings, name="settings"),
    url(r'^signup/step/1/$', views.step_1, name="step_1"),
    url(r'^signup/create/$', views.create_user, name="create_user"),
    url(r'^signup/step/2/$', views.step_2, name="step_2"),
]

nindie/landing/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^login/$', views.user_login, name="login")
]

nindie/nindie/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.shortcuts import redirect


def home_redirect(request):
    return redirect("landing:index")


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace="account")),
    url(r'^playlist/', include('streaming.urls', namespace="streaming")),
    url(r'^$', home_redirect, name="index"),
    url(r'^home/', include("landing.urls", namespace="landing")),
]

nindie/streaming/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^signup/step/(?P<quick_run>[0-9])/$', views.load_artists, name="load_artists"),
    url(r'^delete/(?P<song_id>[0-9])/$', views.delete_song, name="delete_song"),
    url(r"^pick/new/$", views.next_song, name="new_song"),
    url(r"^add/artist/$", views.add_artist, name="add_artist")
]

nindie/account/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User)
    password_reset_code = models.CharField(max_length=100, default="")
    age = models.CharField(max_length=8, default="")
    songs_played = models.IntegerField(default=0)

    def __unicode__(self):
        return self.user.username

# Artist
class Artist(models.Model):
    name = models.CharField(max_length=64, default="")

    def __unicode__(self):
        return self.name

# Song
class Song(models.Model):
    artist = models.ForeignKey(Artist, null=True)
    url = models.CharField(max_length=256, default="")
    title = models.CharField(max_length=64, default="")
    last_played = models.IntegerField(default=0)

nindie/account/views.py
import json
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect

#######################
# Dashboard & Settings#
# #####################
from account.lib.helpers import generate
from account.models import Profile, Song
from streaming.views import pick_random


@login_required
def index(request):
    video_id = pick_random(request)
    video = Song.objects.get(id=video_id)
    video.last_played = 0
    video.save()
    request.user.profile.songs_played += 1
    request.user.profile.save()
    print(request.user.profile.songs_played)
    last_ten = Song.objects.order_by('last_played').all()
    print(video.title + " " + video.url)
    for each in last_ten:
        each.last_played += 1
        each.save()
    if request.user.profile.songs_played < 10:
        last_to_show = request.user.profile.songs_played
    else:
        last_to_show = 10
    return render(request, "dashboard_index.html", {'song': video, 'previous': last_ten[:last_to_show]})


@login_required
def settings(request):
    return render(request, "settings.html")


# ################
# Sign Up Methods#
# ################


def step_1(request):
    return render(request, "step1.html", {'step': 1})


def create_user(request):
    name = request.POST.get('name', 'no name')
    names = name.split(" ")
    name = name.replace(" ", "")
    first = names[0]
    last = names[1]
    email = request.POST.get("email", "example@mail.com")
    password = request.POST.get("password", "HelloWorld1")
    new_user = User.objects.create_superuser(username=name, first_name=first, last_name=last, email=email, password=password)
    new_user.save()
    # Create Profile
    age = request.POST.get("age", "18")
    profile = Profile.objects.create(age=age, password_reset_code=generate(), user=new_user)
    profile.save()
    user = authenticate(username=name, password=password)
    login(request, user)
    return redirect("account:step_2")


@login_required
def step_2(request):
    # Have them upload iTunes XML file
    return render(request, "step2.html", {'step': 2})

nindie/account/templates/dash_layout.html
<!DOCTYPE HTML>
<html>
	<head>
        {% load static from staticfiles %}
		<title>Nindie Dashboard</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-theme.css'%}">
		<!--[if lte IE 8]><script src="{% static 'assets/js/ie/html5shiv.js' %}"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<!--[if lte IE 8]><link rel="stylesheet" href="{% static 'assets/css/ie8.css' %}" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="{% static 'assets/css/ie9.css' %}" /><![endif]-->
	</head>
	<body class="left-sidebar">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header">
					<h1 id="logo"><a href="{% url 'landing:index' %}">Nindie <span>at UB Hacking</span></a></h1>
					<nav id="nav">
						<ul>
							<li class="current"><a href="{% url 'landing:index' %}">Welcome</a></li>
							<li class="submenu">
								<a href="#">Menu</a>
								<ul>
									<li><a href="#">About &amp; Terms</a></li>
									<li><a href="#">Contact</a></li>
                                    {% if request.user.is_authenticated %}
									<li class="submenu">
										<a href="#">Account Menu</a>
										<ul>
											<li><a href="{% url 'account:index' %}">My Music</a></li>
											<li><a href="{% url 'account:settings' %}">Settings</a></li>
											<li><a href="{% url 'landing:logout' %}">Log Out</a></li>
										</ul>
									</li>
                                    {% else %}
                                        <li><a href="{% url 'landing:login' %}">Login</a></li>
                                    {% endif %}
								</ul>
							</li>
							<li><a href="{% url 'account:index' %}" class="button special">Dashboard</a></li>
						</ul>
					</nav>
				</header>

			<!-- Main -->
				<article id="main">
                    {% block content %}
                    {% endblock %}
				</article>

			<!-- Footer -->
				<footer id="footer">

					<ul class="icons">
						<li><a href="#" class="icon circle fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#" class="icon circle fa-facebook"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon circle fa-google-plus"><span class="label">Google+</span></a></li>
						<li><a href="#" class="icon circle fa-github"><span class="label">Github</span></a></li>
						<li><a href="#" class="icon circle fa-dribbble"><span class="label">Dribbble</span></a></li>
					</ul>

					<ul class="copyright">
						<li>&copy; Untitled</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
					</ul>

				</footer>

		</div>

		<!-- Scripts -->
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
            <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.dropotron.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrollgress.min.js' %}"></script>
			<script src="{% static 'assets/js/skel.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js'%}"></script>
			<!--[if lte IE 8]><script src="{% static 'assets/js/ie/respond.min.js' %}"></script><![endif]-->
			<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>

nindie/account/templates/dashboard_index.html
{% extends "dash_layout.html" %}

{% block content %}
    {% load static from staticfiles %}
					<header class="special container" style="background-color: #000000; border-radius: 15px">
						<span class="icon fa-laptop"></span>
                        <h3 id="title">{{ song.title }}</h3>
                    <div style="border-radius: 15px; padding: 1em; color: #56281d">
                        <iframe id="frame" style="border-radius: 20%" height="400" width="40%" src="http://www.youtube.com/embed/{{ song.url }}?autoplay=1&controls=1" frameborder="0" allowfullscreen></iframe>
                        <br>
                        <a href="{% url 'streaming:new_song' %}"><button id="next" class="btn btn-lg"> >> NEXT SONG >> </button></a>
					</div>
                    </header>

					<!-- One -->
						<section class="wrapper style4 container">

							<div class="row 150%">
								<div class="4u 12u(narrower)">

									<!-- Sidebar -->
										<div class="sidebar">
											<section>
												<header>
													<h3>Dashboard Menu</h3>
												</header>
												<footer>
													<ul class="buttons">
														<li><a href="{% url 'account:settings' %}" class="button small">Settings</a></li>
													</ul>
												</footer>
											</section>
										</div>

								</div>
								<div class="8u 12u(narrower) important(narrower)">

									<!-- Content -->
										<div class="content">
											<section>
											    <table class="table-responsive">
                                                    <th class="alert-success alert-dismissable"><tr><td># Behind</td><td>Song</td><td>Artist</td></tr>
                                                    </th>
                                                    <tbody>
                                                    {% for song in previous %}
                                                    <tr>
                                                        <td>{{ song.last_played }}</td>
                                                        <td>{{ song.title }}</td>
                                                        <td>{{ song.artist.name }}</td>
                                                    </tr>
                                                    {% endfor %}
                                                    </tbody>
                                                </table>
											</section>
										</div>

								</div>
							</div>
						</section>
{% endblock %}

nindie/account/templates/settings.html
{% extends "dash_layout.html" %}

{% block content %}
<header class="special container">
						<span class="icon fa-mobile"></span>
						<h2>Account <strong>Settings</strong></h2>
						<p>Looking for a change in your life? You came to the right place!</p>
					</header>

					<!-- One -->
						<section class="wrapper style4 container">

							<!-- Content -->
								<div class="content">
									<section>
										<header>
											<h3>Re-Upload Library</h3>
										</header>
                                        <p>Added some new music to your library? Then reupload your library!</p>
                                        <form action="{% url 'streaming:load_artists' quick_run=1 %}" enctype="multipart/form-data" method="post">
                                            {% csrf_token %}
                                            <input type="file" name="file">
                                            <br/>
                                            <button class="button small" type="submit">Update Library!</button>
                                        </form>
                                        <br/>
									</section>
                                    <section>
                                        <header>
                                            <h3>Add Artist</h3>
                                        </header>
                                        <p>Did we not find an artist that you love? Add them here!</p>
                                        <form class="form-group-sm" enctype="multipart/form-data"  action="{% url 'streaming:add_artist' %}" method="post">
                                            {% csrf_token %}
                                            <input placeholder="Artist Name" class="form-control" style="max-width: 30em" type="text" name="artist" required>
                                            <br>
                                            <button class="button small" type="submit">Add Artist!</button>
                                        </form>
                                    </section>
								</div>

						</section>
{% endblock %}

nindie/account/templates/step1.html
{% extends "dash_layout.html" %}

{% block content %}
    <header class="special container">
        <span class="icon fa-mobile"></span>
        <h2>Account <strong>Sign Up</strong></h2>
        <p>Thank you for trying us out! <br>
            We won't disappoint!</p>
    </header>
    <!-- One -->
    <section class="wrapper style4 container">
        <!-- Content -->
        <div class="content">
            <section>
                <header>
                    <h3 class="col-lg-offset-2">User Info</h3>
                    <form action="{% url 'account:create_user' %}" method="POST">
                        {% csrf_token %}
                        <div class="col-lg-offset-1 col-lg-4 form-group">
                            <label>First and Last Name separated by " "</label>
                            <input type="text" name="name" class="form-control" style="max-width: 250px" placeholder="John Doe" required>
                            <br>
                            <label>Email Address</label>
                            <input type="text" name="email" placeholder="john@gmail.com" class="form-control" style="max-width: 350px" required>
                            <br><label>Password</label>
                            <input type="text" name="password" class="form-control" style="max-width: 300px" placeholder="Password1" required>
                            <br><label>Age</label>
                            <input type="text" class="form-control" style="max-width: 6em" placeholder="18" maxlength="4" name="age" required>
                            <button type="submit" class="pull-right btn btn-lg">Create Me!</button>
                        </div>

                    </form>
                </header>
            </section>
        </div>
    </section>
{% endblock %}

nindie/account/templates/step2.html
{% extends "dash_layout.html" %}

{% block content %}

    {% load static from staticfiles %}
					<header class="special container">
						<span class="icon fa-laptop"></span>
						<h2 id="changetext">Please Upload Your <strong>iTunes XML File</strong></h2>
						<p id="instruct">Don't Worry, it's not that hard :D</p>
                        <span id="bear"></span>
					</header>

                    <script>
                        var change_text = function() {
                            document.getElementById('changetext').innerHTML = "Building Library...";
                            document.getElementById('instruct').innerHTML = "This may take up to a minute";
                            text = "<img src={% static 'images/giphy.gif' %} class='img-responsive' style='border-radius: 10px; max-height: 150px; margin:auto;'/>";
                            document.getElementById('bear').innerHTML = text;
                        };
                    </script>

					<!-- One -->
						<section class="wrapper style4 container">

							<div class="row 150%">
								<div class="4u 12u(narrower)">

									<!-- Sidebar -->
										<div class="sidebar">
											<section>
												<head>
													<h3>Upload it Here!</h3>
                                                    <form class="form-group" enctype="multipart/form-data" method="post" action="{% url 'streaming:load_artists' quick_run=1 %}">
                                                        {% csrf_token %}
                                                        <input type="file" class="btn" name="file">
                                                        <br>
                                                        <button onclick="change_text()" class="pull-right btn btn-lg">Upload File!</button>
                                                    </form>
												</head>
											</section>
										</div>

								</div>
								<div class="8u 12u(narrower) important(narrower)">

									<!-- Content -->
										<div class="content">
											<section class="text-center">
                                                <h3>How do you grab the file you ask?</h3>
                                                <p>Go into your iTunes, and in the top-left, go to "File" --> "Library" --> "Export"
                                                and save the file to a location you will remember. Then, go to 'Choose File' to
                                                    the left and find the file. Then hit Upload and you're all set!</p>
                                                <br/>
                                                <img class="img-responsive" src="{% static 'images/Export_pic.png' %}"/>
											</section>
										</div>

								</div>
							</div>
						</section>
{% endblock %}