nindie/account/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^dashboard/$', views.index, name="index"),
    url(r'^settings/$', views.settings, name="settings"),
    url(r'^signup/step/1/$', views.step_1, name="step_1"),
    url(r'^signup/create/$', views.create_user, name="create_user"),
    url(r'^signup/step/2/$', views.step_2, name="step_2"),
]

nindie/landing/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^login/$', views.user_login, name="login")
]

nindie/nindie/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.shortcuts import redirect


def home_redirect(request):
    return redirect("landing:index")


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('account.urls', namespace="account")),
    url(r'^playlist/', include('streaming.urls', namespace="streaming")),
    url(r'^$', home_redirect, name="index"),
    url(r'^home/', include("landing.urls", namespace="landing")),
]

nindie/landing/models.py
from django.db import models

# Create your models here.

nindie/landing/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login, authenticate


def index(request):
    """
    Landing Page for whole Website
    """
    return render(request, "index.html")


def user_login(request):
    user = authenticate(username="JeremySawyer", password="password")
    login(request, user)
    return redirect("accounts:index")


def user_logout(request):
    logout(request)
    return redirect("landing:index")

nindie/landing/templates/index.html
{% extends "landing_layout.html" %}

{% block content %}
<!-- Banner -->
    {% load static from staticfiles %}
				<section id="banner">

					<!--
						".inner" is set up as an inline-block so it automatically expands
						in both directions to fit whatever's inside it. This means it won't
						automatically wrap lines, so be sure to use line breaks where
						appropriate (<br />).
					-->
					<div class="inner">

						<header>
							<h2>Nindie</h2>
						</header>
						<p>Welcome to <strong>Nindie</strong>,
						<br />
						a music streaming site
                        <br>
                        based around what
                        <br>
                        you want.</p>
						<footer>
							<ul class="buttons vertical">
								<li><a href="#main" class="button fit scrolly">Tell Me More</a></li>
							</ul>
						</footer>

					</div>

				</section>

			<!-- Main -->
				<article id="main">

					<header class="special container">
						<span class="icon fa-music"></span>
						<h2>Do you crave new music? Introducing <strong>Nindie</strong>!
						<br />
						Discover new artists that you'll enjoy.</h2>
					</header>

					<!-- One -->
						<section class="wrapper style2 container special-alt">
							<div class="row 50%">
								<div class="8u 12u(narrower)">

									<header>
										<h2>Extend your <strong>iTunes</strong> Library to discover new music in new ways!</h2>
									</header>
								    <p>We take the artists you already listen to and find similar bands and their music, so you can experiment and grow your taste!</p>
									<footer>
										<ul class="buttons">
											<li><a href="{% url 'account:step_1' %}" class="button">Sign Up Now!</a></li>
										</ul>
									</footer>

								</div>
								<div class="4u 12u(narrower) important(narrower)">

									<ul class="featured-icons">
										<li><span class="icon fa-volume-up"><span class="label"></span></span></li>
										<li><span class="icon fa-laptop"><span class="label"></span></span></li>
                                        <li>Image of iTunes Library</li>
									</ul>

								</div>
							</div>
						</section>

					<!-- Three -->
						<section class="wrapper style3 container special">

							<header class="major">
								<h2>Comes with all these <strong>Cool Features</strong></h2>
							</header>

							<div class="row">
								<div class="6u 12u(narrower)">

									<section>
										<header>
											<h3>Personalized Dashboard</h3>
										</header>
									    <p>A Dashboard with your music and artists is easily displayed for you to add, move and delete artists!</p>
									</section>

								</div>
								<div class="6u 12u(narrower)">

									<section>
										<header>
											<h3>Previous Songs Played</h3>
										</header>
									    <p>Don't you just hate when you're listening to the radio and you miss the name of a good song? We'll have the last 10 songs for you, just in case you are very forgetful!</p>
									</section>

								</div>
							</div>
							<div class="row">
								<div class="6u 12u(narrower)">

									<section>
										<header>
											<h3>Add/Delete Artists</h3>
										</header>
                                        <p>Control your music as you listen!</p>
									</section>

								</div>
								<div class="6u 12u(narrower)">

									<section>
										<header>
											<h3>Stream New Music</h3>
										</header>
									    <p>Blast new music to the point where your ears bleed (Please don't unless you like that), because we offer FREE streaming of music!</p>
									</section>

								</div>
							</div>

							<footer class="major">
								<ul class="buttons">
									<li><a href="#cta" class="button">See More</a></li>
								</ul>
							</footer>

						</section>

				</article>

			<!-- CTA -->
				<section id="cta">

					<header>
						<h2>Ready to try something <strong>cool</strong>?</h2>
						<p>Sign up now! It's free!</p>
					</header>
					<footer>
						<ul class="buttons">
							<li><a href="{% url 'account:step_1' %}" class="button special">Try it Now</a></li>
						</ul>
					</footer>

				</section>
{% endblock %}

nindie/landing/templates/landing_layout.html
<!DOCTYPE HTML>
<html>
	<head>
        {% load static from staticfiles %}
		<title>Nindie</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
	</head>
	<body class="index">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header" class="alt">
					<h1 id="logo"><a href="{% url 'landing:index' %}">Nindie <span>at UB Hacking</span></a></h1>
					<nav id="nav">
						<ul>
							<li class="current"><a href="{% url 'landing:index' %}">Welcome</a></li>
							<li class="submenu">
								<a href="#">Menu</a>
								<ul>
									<li><a href="#">About &amp; Terms</a></li>
									<li><a href="contact.html">Contact</a></li>
                                    {% if request.user.is_authenticated %}
									<li class="submenu">
										<a href="#">Account Menu</a>
										<ul>
											<li><a href="{% url 'account:index' %}">My Music</a></li>
											<li><a href="{% url 'account:settings' %}">Settings</a></li>
											<li><a href="{% url 'landing:logout' %}">Log Out</a></li>
										</ul>
									</li>
                                    {% else %}
                                    <li><a href="{% url 'landing:login' %}">Login</a></li>
                                    <li><a href="{% url 'account:step_1' %}">Sign Up</a></li>
                                    {% endif %}
								</ul>
							</li>
                            {% if request.user.is_authenticated %}
                                <li><a href="{% url 'account:index' %}" class="button special">Dashboard</a></li>
                            {% else %}
							    <li><a href="{% url 'account:step_1' %}" class="button special">Sign Up</a></li>
                            {% endif %}
						</ul>
					</nav>
				</header>
            {% block content %}
            {% endblock %}
        <!-- Footer -->
				<footer id="footer">

					<ul class="icons">
						<li><a href="#" class="icon circle fa-twitter"><span class="label">Twitter</span></a></li>
						<li><a href="#" class="icon circle fa-facebook"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon circle fa-google-plus"><span class="label">Google+</span></a></li>
						<li><a href="#" class="icon circle fa-github"><span class="label">Github</span></a></li>
						<li><a href="#" class="icon circle fa-dribbble"><span class="label">Dribbble</span></a></li>
					</ul>

					<ul class="copyright">
						<li>&copy;Nindie</li><li>Design: Daniel Starner</li>
					</ul>

				</footer>

		</div>

		<!-- Scripts -->
			<script src="{% static 'assets/js/jquery.min.js'%}"></script>
			<script src="{% static 'assets/js/jquery.dropotron.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'assets/js/jquery.scrollgress.min.js' %}"></script>
			<script src="{% static 'assets/js/skel.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>